SocialNetwork/src/java/com/wpsj/model/getAll.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.wpsj.model;

import com.wpsj.da.ProductDataAccess;
import com.wpsj.da.post;
import com.wspj.entity.Account;
import com.wspj.entity.Comment;
import com.wspj.entity.Product;
import java.util.List;

/**
 *
 * @author nam oio
 */
public class getAll {

    public void all() {
    }

    public List<post> getProducts() {
        return new ProductDataAccess().getProducts();
    }

    private String keyword;

    public void setKeyword(String keyword) {

        this.keyword = keyword;

    }

    public List<post> getP() {
        return (List<post>) new ProductDataAccess().getPostId(keyword);
    }

    private String idpost;

    public void setIdpost(String idpost) {

        this.idpost = idpost;

    }

    public List<Comment> getCm() {
        return (List<Comment>) new ProductDataAccess().getCmtId(idpost);
    }

    public List<Account> checkLogin(String user, String password) {
        return (List<Account>) new ProductDataAccess().checkLogin(user, password);
    }

    public boolean createAccount(String user, String password, String fullname) {
        return new ProductDataAccess().createAccount(user, password, fullname);
    }

    public boolean upProfile(String name, String file) {
        return new ProductDataAccess().upProfile(name, file);
    }

     public boolean upAcount(String ussername, String password,String fullname) {
        return new ProductDataAccess().upAcount(ussername, password,fullname);
    }
    private String usname;

    public void setDtailUs(String usname) {
        this.usname = usname;
    }

    public List<post> getPostUsername() {
        return (List<post>) new ProductDataAccess().getPostUser(usname);
    }
 public List<post> getPostUsername(String username) {
        return (List<post>) new ProductDataAccess().getPostUser(usname);
    }
    public boolean deletePost(String id) {
        return new ProductDataAccess().deletePost(id);
    }
public boolean deleteAcount(String id) {
        return new ProductDataAccess().deleteAcount(id);
    }
     public List<Account> getAccount() {
        return (List<Account>) new ProductDataAccess().getAccount();
    }
 public Account getAccountId(String username) {
        return  new ProductDataAccess().getAccount(usname);
    }

  

}

SocialNetwork/web/PersonalPage.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>


<link href="cssmenu/csmenu.css" rel="stylesheet" type="text/css"/>
<script src='https://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js' type='text/javascript'></script>
<script src="cssmenu/jsmenu.js" type="text/javascript"></script>
<link href='https://fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
<div class="header">
     <nav id="fixNav" class="container">
        <a class="fb" href="newjsp.jsp"><i class="fa fa-home" aria-hidden="true"></i> </a>
     
        <a class="fl" href="#"><i class="fa fa-bolt" aria-hidden="true"></i></a>
        <a class="tu" href="#"><i class="fa fa-tumblr"></i></a>
        <a  id='SignIn' class="vi" href="#"><i class="fa fa-pencil" aria-hidden="true"></i></a>
    </nav>
    <div class="inner">
        <div class="user-ui">
            <div class="user-menu-toggle">
                <div class="profile-img" style="background-image:url(${avatar})"></div>
                <span id="btn1" class="simple-arrow fa fa-chevron-up"></span>
            </div>
            <!-- User menu -->
            <div id='comment-editor' style='display:none !important' class="user-menu">
                <div class="user-info">
                    <div class="profile-img"  style="background-image:url(${avatar})"></div>
                    <h3 class="name">${username}</h3>
                    <div class="ui btn normal"> <a href="SignOut" class="button delete"><span>Sign Out</span></a>
                    </div>
                </div>
                <div class="menu-nav">
                    <li></span>Personal page</li>
                    <li ><a id='ed' href="#">Edit</a></li>
                    <li>My comment
                    </li>
                    <li></span>My post</li>
                </div>
            </div>
        </div>
    </div>
</div>





    <!DOCTYPE html>

    <head>
         <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    </head>
        <style>
            #fixNav{


                margin-left: 42%;
    float: left;
    margin-top: 10px;
              width: 300px;
            }
        </style>

        <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
        <link rel="stylesheet prefetch" href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css">

   

    <style>
        .container {
            width: 100%;
            display: table;
            margin: 0;
        }

        nav a {
            display: table-cell;
            color: white;
            width: 14.2%;
            text-align: center;
            font-size: 2em;
            padding: .5em;
        }
        @media (max-width: 768px) {
            nav a {
                font-size: 1.5em;
            }
        }
        nav a:first-child {
            border-radius: 5px 0 0 5px;
        }
        @media (max-width: 768px) {
            nav a:first-child {
                border-radius: 0;
            }
        }
        nav a:last-child {
            border-radius: 0px 5px 5px 0px;
        }
        @media (max-width: 768px) {
            nav a:last-child {
                border-radius: 0;
            }
        }

        nav a:first-child:nth-last-child(1) {
            width: 100%;
        }

        /* two items */
        nav a:first-child:nth-last-child(2),
        nav a:first-child:nth-last-child(2) ~ a {
            width: 50%;
        }

        /* three items */
        nav a:first-child:nth-last-child(3),
        nav a:first-child:nth-last-child(3) ~ a {
            width: 33.3333%;
        }

        /* four items */
        nav a:first-child:nth-last-child(4),
        nav a:first-child:nth-last-child(4) ~ a {
            width: 25%;
        }

        /* five items */
        nav a:first-child:nth-last-child(5),
        nav a:first-child:nth-last-child(5) ~ a {
            width: 20%;
        }

        /* six items */
        nav a:first-child:nth-last-child(6),
        nav a:first-child:nth-last-child(6) ~ a {
            width: 16.666%;
        }

        /* seven items */
        nav a:first-child:nth-last-child(7),
        nav a:first-child:nth-last-child(7) ~ a {
            width: 14.285%;
        }

        /* eight items */
        nav a:first-child:nth-last-child(8),
        nav a:first-child:nth-last-child(8) ~ a {
            width: 12.5%;
        }

        /*
        Assigning link background colors and setting the hover and active states. For quick adding of buttons, perform a search + replace on the 2 letter variable name.
        */
        nav a.fb {
            background: #3B5998;
            text-shadow: 1px 1px 0px #263961;
        }
        nav a.fb:hover {
            color: #3055a3 !important;
            background: #2d4373;
        }
        nav a.fb:active {
            color: #3B5998;
            background: #1e2e4f;
        }

        nav a.tw {
            background: #55ACEE;
            text-shadow: 1px 1px 0px #1689e0;
        }
        nav a.tw:hover {
            color: #4cadf7 !important;
            background: #2795e9;
        }
        nav a.tw:active {
            color: #55ACEE;
            background: #147bc9;
        }

        nav a.gp {
            background: #DD4B39;
            text-shadow: 1px 1px 0px #ac2d1e;
        }
        nav a.gp:hover {
            color: #e9422d !important;
            background: #c23321;
        }
        nav a.gp:active {
            color: #DD4B39;
            background: #96271a;
        }

        nav a.ig {
            background: #517FA4;
            text-shadow: 1px 1px 0px #385771;
        }
        nav a.ig:hover {
            color: #4580b0 !important;
            background: #406582;
        }
        nav a.ig:active {
            color: #517FA4;
            background: #2f4a60;
        }

        nav a.fl {
            background: #FF0084;
            text-shadow: 1px 1px 0px #b3005c;
        }
        nav a.fl:hover {
            color: #ff0084 !important;
            background: #cc006a;
        }
        nav a.fl:active {
            color: #FF0084;
            background: #99004f;
        }

        nav a.tu {
            background: #32506D;
            text-shadow: 1px 1px 0px #1a2a39;
        }
        nav a.tu:hover {
            color: #2a5075 !important;
            background: #22364a;
        }
        nav a.tu:active {
            color: #32506D;
            background: #121d27;
        }

        nav a.vi {
            background: #00BF8F;
            text-shadow: 1px 1px 0px #007356;
        }
        nav a.vi:hover {
            color: #00bf8f !important;
            background: #008c69;
        }
        nav a.vi:active {
            color: #00BF8F;
            background: #005943;
        }
.header {
    position: fixed;
    z-index: 100000;
    margin-top: -30px;
}
#fixNav {
    margin-left: 38%;}
    </style>

</head>





































 <jsp:useBean class="com.wpsj.model.getAll" id="cm" scope="request"/>



<div id="container">

  <a class="img" href="#">
  <div class="img__overlay img__overlay--red">Hey!</div>
  <img src="${avatar1}" />
</a>
<div id="content">
		<h1>${username1}</h1>
		  
                 <div class="container">
        <ul class="posts">
            <c:forEach items="${cm.postUsername}" var="product">
                <c:if test="${product.post_username!=null}">
                <li class="post">
                    <div class="post-content">
                        <header><a href="https://twitter.com/@kamciesla">${product.post_username}</a></header>
                            <c:if test = "${product.post_image!=''}">
                            <img src="${product.post_image}"/>
                        </c:if>
                        <footer> <p id="v">

                                ${product.post_content}
                            </p>
                            <a href="https://kamilciesla.pl"><i class="fa fa-heart" aria-hidden="true"></i></a>
                            <a href="Comment?id=${product.post_id}"><i class="fa fa-comment" aria-hidden="true"></i></a>
                            <a href="https://twitter.com/@kamciesla"><i class="fa fa-paper-plane" aria-hidden="true"></i></a></footer>
                            <c:if test = "${username==username1}">
                            <a href="DeletePost?idpost=${product.post_id}"><i class="fa fa-trash" aria-hidden="true"></i></a></footer>
        </c:if>
                    </div>
                </li>
                </c:if>
            </c:forEach>

        </ul>

    </div>
	</div>
</div>



  <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
        <link rel="stylesheet prefetch" href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css">


<style>
 @import url(https://fonts.googleapis.com/css?family=Raleway:400,500,600);
body {
  background: url("http://emilcarlsson.se/assets/forest-green-blue-gradient.jpg") no-repeat center center fixed;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
  font-family: 'Raleway', sans-serif;
}

#container {
  width: 90%;
  margin: 30px auto 0 auto;
  background: #FFF;
  border-radius: 10px;
  box-shadow: 0 0 30px rgba(0, 0, 0, 0.3);
  -webkit-box-shadow: 0 0 30px rgba(0, 0, 0, 0.3);
  overflow: hidden;
}
#container #hero-img {
  width: 100%;
  height: 200px;
  background: url("http://emilcarlsson.se/assets/forest.jpg") no-repeat center center;
  background-size: cover;
}
#container #profile-img {
  width: 160px;
  height: 160px;
  margin: -80px auto 0 auto;
  border: 6px solid #FFF;
  border-radius: 50%;
  box-shadow: 0 0 5px rgba(90, 90, 90, 0.3);
}
#container #profile-img img {
  width: 100%;
  background: #FFF;
  border-radius: 50%;
}
#container #content {
  text-align: center;
  width: 90%;
  margin: 0 auto;
  padding: 0 0 50px 0;
  
}
#container #content h1 {
  font-size: 29px;
  font-weight: 500;
  margin: 20px 0 0 0;
}
#container #content p {
  font-size: 18px;
  font-weight: 400;
  line-height: 1.4;
  color: #666;
  margin: 15px 0 40px 0;
}
#container #content a {
  color: #CCC;
  font-size: 14px;
  margin: 0 10px;
  transition: color .3s ease-in-out;
  -webkit-transition: color .3s ease-in-out;
}
#container #content a:hover {
  color: #2ecc71;
}


   .post {
    margin-top: 20px;
    
    position: relative;
}
    
    </style>
    
    
    <style>
        
        
        body {
  font: bold 13px Helvetica, Arial, sans-serif;
  
      background: #41cac0;
}

a {
  color: #a2a2a2;
  text-decoration: none;
  -webkit-transition: color .3s ease;
  transition: color .3s ease;
}
footer a {
  margin-right: 10px;
}


a:hover {
  color: #666;
}

.container {
  max-width: 650px;
  width: 100%;
  margin: 0 auto;
}

.no-posts {
  padding: 50px 10px 30px 100px;
  text-align: center;
  color: #fff;
}

.posts {
  
  list-style: none;
  margin: 20px auto;
  padding: 0;
  width: 100%;
    margin-top: 80px;
}
.posts .post {
  margin-top: 20px;
  
  position: relative;
}
.posts .post-avatar {
  background: #fff url("http://on.be.net/1Noq5Sf") center/100%;
  height: 80px;
  width: 80px;
  border-radius: 4px;
  position: absolute;
  left: -100px;
  top: 0;
}
.posts .post-avatar.post-avatar--fixed {
  position: fixed;
  left: 50%;
  top: 20px;
  margin-left: -325px;
}
.posts .post-avatar.post-avatar--absolute {
  position: absolute;
  bottom: 0;
  left: 0;
  margin-left: -100px;
  top: auto;
}
.posts .post-content {
  background: #fff;
  border-radius: 4px;
  width: 100%;
}
.posts .post-content img {
  width: 100%;
}
.posts .post-content header, .posts .post-content footer {
  padding: 15px 20px;
}













.img {
  border-radius: 100%;
  color: #fafafa;
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
  -webkit-box-flex: 0;
  -ms-flex: 0 0 200px;
  flex: 0 0 200px;
  height: 200px;
  -webkit-box-pack: center;
  -ms-flex-pack: center;
  justify-content: center;
  overflow: hidden;
  position: relative;
  width: 200px;
      margin-left: 500px;
    margin-top: 100px;
}
.img img {
  height: 100%;
}

.i
.img {
  -webkit-animation: fadeIn 0.5s;
  animation: fadeIn 0.5s;
  border: 4px solid #c0c0c0;
 
     
}


@-webkit-keyframes fadeIn {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}
@keyframes fadeIn {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}



    </style>

SocialNetwork/web/Register.jsp
<div class="cont">
  <div class="main-box">
    <div class="log">
      <form action="Register">
        <h2>Register</h2>
       
  <i class="fa fa-fw fa-user" aria-hidden="true"></i>
        <input type="text"
               name="username"
               class="user"
               placeholder="Username"/>
       
        
     <i class="fa fa-list-alt" aria-hidden="true"></i>
        <input type="text"
               name="fullname"
               class="user"
               placeholder="Full nam"/>
        <i class="fa fa-fw fa-lock" aria-hidden="true"></i>
        <input type="password" 
               name="password"
               class="pass"
               placeholder="Password"/>

        <button                class="login">Register</button>
      </form>
           <a href="login.jsp">Login</a>
    </div>
  </div> 
</div>

<link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
<link rel="stylesheet prefetch" href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css">

<style>
    
    @import url("https://fonts.googleapis.com/css?family=Raleway:300,400,700");

* {
 
  padding: 0;
  outline: none;
  box-sizing: border-box;
  font-family: "Raleway", sans-serif;
}
a{
    color: #41cac0;
}
body {
  background: #41cac0;
}

.cont {
  position: relative;
  width: 28%;
  height: 550px;
  margin: 10px auto;
}

.main-box {
  width: 100%;
  height: 112%;
  text-align: center;
  background: #1d4a5f;
  box-shadow: 0px 0px 40px 1px #262626;
}

.log {
  position: relative;
  top: 20%;
  width: 100%;
  height: 75%;
  padding: 18px 15px;
}

h2,
.user,
.pass {
  display: block;
}

h2 {
  text-align: center;
  color: #4fdac3;
  font-weight: 600;
  font-size: 30px;
  letter-spacing: 3px;
  margin-bottom: 50px;
}

.user,
.pass {
  width: 85%;
  height: 45px;
  border: none;
  color: white;
  margin: auto;
  padding-left: 40px;
  font-size: 18px;
  font-weight: 500;
  margin-bottom: 25px;
  background: #0e2d3f;
}

input::placeholder {
  color: #eaeaea;
  font-size: 15px;
  font-weight: lighter;
}

.fa {
  position: relative;
  color: #fff;
  font-size: 16px;
  left: -36%;
  top: 33px;
}

.login {
  color: #fff;
  cursor: pointer;
  width: 85%;
  height: 50px;
  border: none;
  font-size: 22px;
  font-weight: 500;
  margin-top: 2%;
  box-shadow: 0px 2px 3px 5px rgba(42, 42, 42, 0.23);
  background: linear-gradient(to right, #4ce3c2, #35c1c0);
}

@media only screen and (min-width: 280px) {
  .cont {
    width: 90%;
  }
}

@media only screen and (min-width: 480px) {
  .cont {
    width: 60%;
  }
}

@media only screen and (min-width: 768px) {
  .cont {
    width: 40%;
  }
}

@media only screen and (min-width: 992px) {
  .cont {
    width: 30%;
  }
}

</style>

SocialNetwork/web/admin_addAcound.jsp
<%-- 
    Document   : add
    Created on : Feb 28, 2018, 1:02:36 AM
    Author     : nam oio
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
       <title>List Product!</title>
    </head>
  
     <a href="search.jsp">Search</a>
     <a href="add.jsp">add</a>
       <a href="view.jsp">view</a>
       <link href="css/input.css" rel="stylesheet" type="text/css"/>
    <body>
       <form action="add">
           
           
         <div class="row">
  <span>
    <input name="id" class="swing" id="artist" type="text" placeholder=""><label for="artist">ID</label>
  </span>
  <span>
    <input name="name" class="swing" id="song" type="text" placeholder=""><label for="song">NAME</label>
  </span>
  <span>
    <input name="desc" class="swing" id="eyes" type="text" placeholder=""><label for="eyes">DESC</label>
  </span>
</div>
           
           
           
           
        <input type="submit"/>
    </form>
    </body>
</html>

SocialNetwork/web/admin_editAccount.jsp
<%-- 
    Document   : edit
    Created on : Feb 28, 2018, 3:09:14 AM
    Author     : nam oio
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
        <link href="css/input.css" rel="stylesheet" type="text/css"/>
    </head>
    
    <body>
        <form action="admin_editAccount" method="post">
            
                   <div class="row">
  <span>
    <input name="username" value="${ad_username}" class="swing" id="artist" type="text" placeholder=""><label for="artist">ID</label>
  </span>
  <span>
    <input name="password" value="${ad_password}" class="swing" id="song" type="text" placeholder=""><label for="song">NAME</label>
  </span>
  <span>
    <input name="fullname" value="${ad_fullname}" class="swing" id="eyes" type="text" placeholder=""><label for="eyes">DESC</label>
  </span>
</div>
            
            
            
            
               
        <input type="submit"/>
            
            </form>
    </body>
</html>

SocialNetwork/web/admin_listAccount.jsp
<%-- 
    Document   : result
    Created on : Feb 27, 2018, 3:01:32 PM
    Author     : Puarinnnn
--%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <link href="cssadacount/newcss.css" rel="stylesheet" type="text/css"/>
        <link href="cssadacount/input.css" rel="stylesheet" type="text/css"/>
        <link href="cssadacount/newcss.css" rel="stylesheet" type="text/css"/>
        <script src="js/newjavascript.js" type="text/javascript"></script>
        <script src="js/jquery-3.3.1.min.js" type="text/javascript"></script>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>List Product!</title>
      </head>
    <h1>List Product!</h1>
    <a href="search.jsp">Search</a>
    <a href="add.jsp">add</a>
    <a href="view.jsp">view</a>
    <jsp:useBean class="com.wpsj.model.getAll" id="finder1" scope="request"/>
    <div class="tbl-header">
        <table cellpadding="0" cellspacing="0" border="0">
            <thead>
                <tr>
                    <th>ac_username</th>
                    <th>ac_password</th>
                    <th>ac_fullname</th>
                    <th>ac_avatar</th>
                     <th></th>
                    <th></th>
                    <th></th>
                    
                </tr>
            </thead>
        </table>
    </div>
  
    <div class="tbl-content">
        <table cellpadding="0" cellspacing="0" border="0">
            <c:forEach items="${finder1.account}" var="ac">  <c:forEach items="${finder1.account}" var="ac"></c:forEach>
            <c:forEach items="${finder1.account}" var="ac">
                <tr>
                    <td><c:out value="${ac.ac_username}"/></td>
                    <td><c:out value="${ac.ac_password}"/></td>
                    <td><c:out value="${ac.ac_fullname}"/></td>
                     <td><c:out value="${ac.ac_avatar}"/></td>
                     <td></td>
                    <td> 
                        <div class="buttons">
                            <a href="admin_editAccount?username=${ac.ac_username}" class="button edit"><span>Edit</span></a>
                        </div>
                    </td>
                    <td>

                        <div class="buttons">
                            <a href="admin_deleteAccount?username=${ac.ac_username}" class="button delete"><span>Delete</span></a>
                        </div>

                    </td>


                </tr>
            </c:forEach>   </c:forEach>   
        </table></div>

</html>

SocialNetwork/web/login.jsp
<div class="cont">
  <div class="main-box">
    <div class="log">
      <form action="Login">
        <h2>Login</h2>
        <i class="fa fa-fw fa-user" aria-hidden="true"></i>
        <input type="text"
               value="${username}"
               name="username"
               class="user"
               placeholder="Username"/>

        <i class="fa fa-fw fa-lock" aria-hidden="true"></i>
        <input type="password" value="${password}"
               name="password"
               class="pass"
               placeholder="Password"/>

        <button                class="login">LOGIN</button>
       
      </form>
         <a href="Register.jsp">Register</a>
    </div>
  </div> 
</div>

<link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
<link rel="stylesheet prefetch" href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css">

<style>
    
    @import url("https://fonts.googleapis.com/css?family=Raleway:300,400,700");

* {
 
  padding: 0;
  outline: none;
  box-sizing: border-box;
  font-family: "Raleway", sans-serif;
}


body {
  background: #41cac0;
  
}
a{
    color: #41cac0;
}
.cont {
  position: relative;
  width: 28%;
  height: 550px;
  margin: 10px auto;
}

.main-box {
  width: 100%;
  height: 100%;
  text-align: center;
  background: #1d4a5f;
  box-shadow: 0px 0px 40px 1px #262626;
}

.log {
  position: relative;
  top: 20%;
  width: 100%;
  height: 75%;
  padding: 18px 15px;
}

h2,
.user,
.pass {
  display: block;
}

h2 {
  text-align: center;
  color: #4fdac3;
  font-weight: 600;
  font-size: 30px;
  letter-spacing: 3px;
  margin-bottom: 50px;
}

.user,
.pass {
  width: 85%;
  height: 45px;
  border: none;
  color: white;
  margin: auto;
  padding-left: 40px;
  font-size: 18px;
  font-weight: 500;
  margin-bottom: 25px;
  background: #0e2d3f;
}

input::placeholder {
  color: #eaeaea;
  font-size: 15px;
  font-weight: lighter;
}

.fa {
  position: relative;
  color: #fff;
  font-size: 16px;
  left: -36%;
  top: 33px;
}

.login {
  color: #fff;
  cursor: pointer;
  width: 85%;
  height: 50px;
  border: none;
  font-size: 22px;
  font-weight: 500;
  margin-top: 2%;
  box-shadow: 0px 2px 3px 5px rgba(42, 42, 42, 0.23);
  background: linear-gradient(to right, #4ce3c2, #35c1c0);
}

@media only screen and (min-width: 280px) {
  .cont {
    width: 90%;
  }
}

@media only screen and (min-width: 480px) {
  .cont {
    width: 60%;
  }
}

@media only screen and (min-width: 768px) {
  .cont {
    width: 40%;
  }
}

@media only screen and (min-width: 992px) {
  .cont {
    width: 30%;
  }
}

</style>

SocialNetwork/web/munu.jsp
<button id='rdit'>Sign in</button>






<div style='display:none !important' class='login'>
    <button class='close' id='close'></button>
    <form action="FileUploadServlet" method="post" enctype="multipart/form-data">

      
<textarea name="content" onkeyup="textAreaAdjust(this)"></textarea>
        <input name="file" type='file' onchange="readURL(this);" />
        <img class="v" style='display:none !important' id="blah" src="" alt="your image" />
        <input type="submit" value="Submit">
    </form>
</div>








<script src="csscomment/jquery-3.3.1.js" type="text/javascript"></script>
<script src="csscomment/jquery-3.3.1.min.js" type="text/javascript"></script>
<div class='login'>
    <button class='close' id='close'></button>
    <form action="FileUploadServlet" method="post" enctype="multipart/form-data">
<div class="media-container">
	<span class="media-overlay">
		<input type="file" id="media-input" accept="image/*">
		<i class="glyphicon glyphicon-edit media-icon"></i>
	</span>
	<figure class="media-object">
		<img class="img-object" src="http://placehold.it/200x200">
	</figure>
</div>
<div class="media-control">
	<a class="edit-profile">Edit Profile</a>
	<a class="save-profile">Save Profile</a>
</div>
    </form>
</div>

<link href="csseditprototype/prototype.css" rel="stylesheet" type="text/css"/>

<script>

    var btn_save = $(".save-profile"),
	btn_edit = $(".edit-profile"),
	img_object = $(".img-object"),
	overlay = $(".media-overlay"),
	media_input = $("#media-input");

btn_save.hide(0);
overlay.hide(0);

$('.edit-profile').on('click', function() {
	$(this).hide(0);
	$(this).siblings().fadeToggle(300);
	overlay.fadeToggle(300);
});

media_input.change(function() {
	if (this.files && this.files[0]) {
		var reader = new FileReader();
		
		reader.onload = function(e) {
			img_object.attr("src", e.target.result);
		};
		
		reader.readAsDataURL(this.files[0]);
	}
});
    
  
    
   
</script>